import 'package:flutter/material.dart';

class TermsandPrivacyPolicy extends StatelessWidget {
  const TermsandPrivacyPolicy({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(padding: 
      EdgeInsets.all(8.0),child: Text("Privacy Policy \n Polkawallet.io (“We”; “us”; or “our”) are committed to protecting and respecting your privacy. This policy (together with our terms of use on our websites https://polkawallet.io (the “Sites“) and any other documents referred to on it) sets out the basis on which any personal data we collect from you, or that you provide to us, will be processed by us. Please read the following carefully to understand our views and practices regarding your personal data and how we will treat it. \n  What data do we collect from you? \n The Substrate based blockchain clients written with Flutter in the programming language Dart known as Polkawallet does not collect information from you, however any information you publish onto a blockchain like Polkadot is public by design. If you go to our Sites or utilise other services, we may collect and process the following personal data about you:Information you give us. This is information about you that you give us by filling in forms on our Sites, filling in forms on the sites of third party vendors providing us with a service, or by corresponding with us by phone, e-mail or otherwise. It includes information you provide when you agree to our contributors license agreement (“CLA”), apply for a job on our Sites, ask to receive our newsletter and when you report a problem with our Sites. The information you give us may include your name, address, e-mail address and phone number and job application information (e.g. your CV, education data, and picture).Information we collect about you. With regard to each of your visits to our Sites we may automatically collect the following information:technical information, including the Internet protocol (IP) address used to connect your computer to the Internet, browser type and version, and versions, operating system and platform; andinformation about your visit, including the full Uniform Resource Locators (URL), page response times and download errors.Information we receive from other sources. This is information we receive about you if you use any of the other websites we operate or the other services we provide or, to the extent permitted by law, publicly accessible information about you on e.g. business social media. We are working closely with third parties (including, for example, recruitment services providers). We will notify you when we receive information about you from them and the purposes for which we intend to use that information."),),
    );
  }
}